name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write      # Required for aws-actions/configure-aws-credentials
  contents: read       # Required for actions/checkout

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        role-to-assume: arn:aws:iam::803205869942:role/github-actions-usa-reddragon.github.io
        aws-region: us-east-1

    - name: Push to S3
      run: aws s3 sync . s3://mcswainsoftware

    - name: Clear Cloudfront Cache
      run: aws cloudfront create-invalidation --distribution-id EV4V4UO7JH2SB --paths "/*"
